on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

name: data-update-data-convert

jobs:
  update-convert-data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # scripts
      - name: update-data
        run: Rscript "data-raw/update-data.R"
      - name: convert-data
        run: Rscript "data-raw/convert-rda-to-csv.R"

      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "data update" || echo "No changes to commit"
          git pull --rebase
          git push
